// import Head from 'next/head'
import styles from "../styles/Login.module.css";

export default function Login() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    // </div>
    <>
    <div className={styles.loginpage}>
      <div className={styles.container}>
        <div className={styles.box}>
          <img src="/img/logo.png" className={styles.logo} />

          <h2 className={styles.logotext}>Mine</h2>
          <form className={styles.loginForm}>
            <div className={styles.inputBox}>
              <input type="text" required />
              <label>Email</label>
            </div>
            <div className={styles.inputBox}>
              <input type="password" required />
              <label>Password</label>
            </div>
            <div className={styles.inputBox}>
              <input type="password" required />
              <label>Confirm Password</label>
            </div>
            <button
              type="button"
              className={styles.loginButton}
              value="Sign in"
            >
              Sign in
            </button>
            <button
              type="button"
              className={styles.loginButton}
              value="Sign up"
            >
              Sign up
            </button>
            <br />
            <img src="~/assets/img/add-user.png" className={styles.logo1} />
            <img src="~/assets/img/login-user.png" className={styles.logo1} />
            <img src="~/assets/img/google.png" className={styles.logo1} />
          </form>
          <h1 className={styles.descryption}>Personalise Your Memories</h1>
        </div>
      </div>
    </div>
    </>
  );
}
